### ISSUE TITLE
add client tests for 'get genes for segment' and 'get segments for gene'

### ISSUE THREAD

**Issue by dhrogers** [lanl/4DGB#11]
Update the google actions for the client test to test the two new calls above.

Correct values for test.00 that should produce results are

get_genes_for_segment(0, 8)
get_segments_for_gene(0, 'Btbd35f23')
get_segments_for_gene(0, 'Btbd35f24')

I increased the 'interval' value for the test.00/project.json file in order to make this work. This shouldn't impact other tests, but if we find a problem, we will have to change things around.

**Comment by ricardosida** [comment]
I just created a pull request for the test_gentk file
let me know if I did it correctly

**Comment by dhrogers** [comment]
Looks good. I merged it and deleted the branch on the server.

Take a look at the master now, and make sure it's correct. The test should be running now.

- David
________________________________________
From: ricardosida ***@***.***>
Sent: Friday, July 16, 2021 12:24:01 PM
To: lanl/4DGB
Cc: Rogers, David Honegger; Assign
Subject: [EXTERNAL] Re: [lanl/4DGB] add client tests for 'get genes for segment' and 'get segments for gene' (#11)

I just created a pull request for the test_gentk file
let me know if I did it correctly

**Comment by dhrogers** [comment]
Nice work - looks like the tests all passed in the new master!

Now the workflow is going to be:

1. add new data to the database
2. add client and server methods to access the new data
3. add a test to test_gentk

We're in good shape. Take a bit of time to update your slides for Monday, and we can check in at the 11am meeting.

Do you have anything to work on, or do you need something else?

- David
________________________________________

**Comment by ricardosida** [comment]
Sounds good!
I'll start working on the presentation

Thank you 
-Ricardo

**Comment by dhrogers** [comment]
@ricardosida - can you close this issue, and add a final comment?
