### ISSUE TITLE
add test for get_contactmap to testing/test_gentk.py (on js-client-test branch)

### ISSUE THREAD

**Issue by dhrogers** [lanl/4DGB#19]
Client API has one final call to be added to testing/test_gentk.py:

    get_contactmap

This should be added on branch js-client-test. There is a skeleton call 'test_contactmap' in testing/test_gentk.py. It needs to be filled out with a valid test.

The contact map ID that you should test is '0'

**Comment by ricardosida** [comment]
Done testing with 0, do you want me to do edge cases with -1 and 2?  or just leave it with 0?

**Comment by dhrogers** [comment]
Yes. Add -1 and 2 as edge cases.

**Comment by ricardosida** [comment]
Done testing, should I create a pull request?

**Comment by dhrogers** [comment]
Yes

**Comment by dhrogers** [comment]
Completed.
