### ISSUE TITLE
create examples directory and first example

### ISSUE THREAD

**Issue by dhrogers** [lanl/4DGB#24]

**Comment by dhrogers** [comment]
@ricardosida - can you add instructions to this discussion about how to run the example?

**Comment by ricardosida** [comment]
I apologize for the late response

To run the example locally first you need to have installed jupyter lab, ipympl, and pypac.
To install those:
In a terminal run the following conda and pip commands:
     conda install -c conda-forge ipympl
     pip install pypac
     conda install -c conda-forge jupyterlab
 
After that, close that terminal.

Activate a jupyter lab in a terminal with the command:
    jupyter lab
 
Use the GUI to navigate to the directory of your notebook (4DGB), and then go to the folder "example", then click on  "gentk.ipynb"

Before running the notebook, we need to make a release locally 

    ./bin/make_release test.00 8000
    pushd release/test.00
    python gtkserver.py localhost.yaml

Finally, just run the notebook and you should see the 3D plot


Let me know if it works

**Comment by dhrogers** [comment]
Done!
