### ISSUE TITLE
Make contactmap widget repositionable

### ISSUE THREAD

**Issue by dhrogers** [lanl/4DGB#25]
Contact map widget positions axes incorrectly when it is not full size in a div. For example, adjusting the size to be 250x250 with the current master compare app positions axes to the right of the contact map viz:

![example](https://user-images.githubusercontent.com/5340672/128366675-b44483e4-d02d-4959-8fb0-0c93a30e5a55.png)

**Comment by camtauxe** [comment]
Fixed in PR #58
